version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: op
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: diet_craft

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
